[workspace]
members = [
    "crates/*"
]

[workspace.package]
version = "0.0.1-alpha.1"
authors = ["Benedikt Schwab"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tum-gis/egraphics"

[workspace.dependencies]
thiserror = "1.0"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
gltf = "1.0.0"
gltf-json = "1.0.0"
nalgebra = "0.31.1"
